eve:
    client:
      accessTokenUri: https://login.eveonline.com/oauth/token
      userAuthorizationUri: https://login.eveonline.com/oauth/authorize
      scope: publicData fleetRead fleetWrite remoteClientUI esi-location.read_location.v1 esi-location.read_ship_type.v1 esi-fleets.read_fleet.v1 esi-fleets.write_fleet.v1 esi-ui.write_waypoint.v1
      tokenName: oauth_token, refresh_token
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: https://login.eveonline.com/oauth/verify
logging:
  level:
    org.springframework.security: DEBUG